### ISSUE TITLE
Please provide a soname

### ISSUE THREAD

**Issue by solopasha** [hyprwm/hyprlang#14]
Can you please provide a SONAME for the library?

Installing something in usr/lib without a SONAME is painful and discouraged by the Fedora guidelines (where I want to package it).

**Comment by fufexan** [comment]
SONAME already exists though
```sh
› objdump /nix/store/943y7w284hq23fw0hdqgsqbsgp9a5jdd-hyprlang-0.pre+date=2024-01-02_3fdceef/lib/libhyprlang.so -p | rg -i soname
  SONAME               libhyprlang.so
  ```

**Comment by solopasha** [comment]
I mean versioning (libfoo.so.1)

**Comment by fufexan** [comment]
Done in 8118461c52641d6c099742b5c32ff26678efe930.
