### ISSUE TITLE
Error building Hyperlang

### ISSUE THREAD

**Issue by Kiirx** [hyprwm/hyprlang#16]
When building with the commands in the readme, I get this following error:
```
 getconf: variable not recognized "NPROCESSORS_CONF" 
```

and if I try to pass this error by only doing
```
cmake --build ./build --config Release --target hyprlang
```

it will tell me that `#include <format>` cannot be found, I have libfmt-dev installed

OS: Debian 12 (bookworm)
Kernel: 6.1.0-17-amd64
DE: Hyprland

**Comment by fufexan** [comment]
You need at least GCC 13. Debian's is probably older.

**Comment by Kiirx** [comment]
oh yep its gcc 12.2.0

**Comment by RAprogramm** [comment]
```sh
❯ gcc --version
gcc (GCC) 13.2.1 20230801
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
---
```sh
cmake --build ./build --config Release --target hyprlang -j`nproc 2>/dev/null || getconf NPROCESSORS_CONF`
getconf: Unrecognized variable `NPROCESSORS_CONF`'
```

**Comment by vaxerski** [comment]
idk what system doesn't ship either `nproc` or `getconf NPROCESSORS_CONF` but you can just manually input the amount of cores in thta case

**Comment by RAprogramm** [comment]
> idk what system doesn't ship either `nproc` or `getconf NPROCESSORS_CONF` but you can just manually input the amount of cores in thta case

It is latest Arch

**Comment by vaxerski** [comment]
do you not have coreutils installed? dafoq

**Comment by RAprogramm** [comment]
> do you not have coreutils installed? dafoq

Hmm, I think coreutils is default package. (ls,mv,cp,rm,cat, etc.. )
