### ISSUE TITLE
Hyprlang dependency issue

### ISSUE THREAD

**Issue by HASKADOG** [hyprwm/hyprlang#22]
I tried to run sudo pacman -Syyu and got this:
` installing hyprlang (0.4.0-1) breaks dependency 'libhyprlang.so=0-64' required by xdg-desktop-portal-hyprland`

**Comment by Are10** [comment]
Getting the same issue for hyprpaper as well, so it's probably not the xdg-portal.
`installing hyprlang (0.4.0-1) breaks dependency 'libhyprlang.so=0-64' required by hyprpaper`
`installing hyprlang (0.4.0-1) breaks dependency 'libhyprlang.so=0-64' required by xdg-desktop-portal-hyprland`

**Comment by vaxerski** [comment]
that's a problem with arch and not hyprlang

**Comment by vaxerski** [comment]
looks like arch updated hyprlang to 0.4.0 but xdph and hyprpaper weren't updated to depend on 0.4.0 and the updated versions are in Extra-staging instead.

classic arch

**Comment by robbmj** [comment]
> looks like arch updated hyprlang to 0.4.0 but xdph and hyprpaper weren't updated to depend on 0.4.0 and the updated versions are in Extra-staging instead.
> 
> classic arch

https://archlinux.org/packages/extra-staging/x86_64/xdg-desktop-portal-hyprland/
https://archlinux.org/packages/extra-staging/x86_64/hyprpaper/

Those ones?

**Comment by robbmj** [comment]
Gotcha, I assume these will make their way into `Extra` some time soon? I honestly don't know how package promotion works in arch land, or even who/what does it.

**Comment by robbmj** [comment]
Arch fixed the issue, they updated the packager in Extra.

**Comment by mylinuxforwork** [comment]
Thanks for the update.
