### ISSUE TITLE
Invalid configuration lines for a comment block (multiple hash)

### ISSUE THREAD

**Issue by TeChn4K** [hyprwm/hyprlang#23]
From my last upgrade, all my comment blocks are reported as error.

```
###
### Monitors
###
```
^ not good

```
# ##
# ## Monitors
# ##
```
^ good

**Comment by vaxerski** [comment]
because they are invalid lines

**Comment by TeChn4K** [comment]
Precisely, this ticket was about how weird this invalidity is.

**Comment by TeChn4K** [comment]
Are you not supposed to be able to write anything after the comment char, like any other language?

Anyway, not very important, config file updated.

**Comment by vaxerski** [comment]
`##` is an escape for a `#` so your line gets turned into actual `#####` and `#####` does not seem like a valid line does it

**Comment by TeChn4K** [comment]
OK thanks for these details, I understand better
