### ISSUE TITLE
Support for values containing ":" characters

### ISSUE THREAD

**Issue by Safenein** [hyprwm/hyprlang#29]
With the hyprlang migration of Hyprland, I am now unable to configure some devices due to ":" character present in its name.

For example:

```
device {
  name = elan9008:00-04f3:2f29-stylus
}
```

This snippet generate error "special category's first value must be the key. Key for <device> is <name>" in Hyprland due to misinterpretation of name value.

It would be nice to be able to quote value so that it is interpreted as a string. It would look like this for example:

```
device {
  name = "elan9008:00-04f3:2f29-stylus"
}
```

**Comment by vaxerski** [comment]
This was a bug. No quotes necessary, it's now fixed.
