### ISSUE TITLE
Comment escaping with `##` should not apply to lines that begin with `#`

### ISSUE THREAD

**Issue by m-bartlett** [hyprwm/hyprlang#30]
After upgrading to Hyprland 0.36.0 I had dozens of configuration errors in the error popup. The issue ended up being that I was using `##` to prefix section titles in my config to distinguish them from regular commented lines and to make the config easier to search. The changelog for 0.36.0 mentions:

> `##` is now properly treated as an escaped `#`.

but I feel this should be ignored for lines where the first character is `#` since it seems unexpected, but perhaps there's a scenario where a config line could begin with a literal `#` that I'm not aware of.

**Comment by vaxerski** [comment]
Technically you're right, there should be no line beginning with `#`
