### ISSUE TITLE
handle env var globbing/splitting

### ISSUE THREAD

**Issue by kojq** [hyprwm/hyprlang#33]
From hyprwm/Hyprland/issues/5172, we should handle env var globbing/splitting.

**Comment by kojq** [comment]
### Description:

Doing the following with nothing in config yields `Hyprarchfoot`:

```
workspace = special:hi, on-created-empty:foot -H echo Hypr$HOSTNAME$TERM
bind = WIN, N, togglespecialworkspace, hi
```

atm, we can define them in config as well, and the info will be passed into terminal, yielding `hello`:

```
$HI=hello
workspace = special:hi, on-created-empty:foot -H echo $HI
bind = WIN, N, togglespecialworkspace, hi
```

### Problems:

1) Parse example: $TERMINAL as $TERM with INAL appended or not (becomes `footINAL`)
```
$TERMINAL=foot
workspace = special:hi, on-created-empty:foot -H echo $TERMINAL
bind = WIN, N, togglespecialworkspace, hi
```

2) #32 wants to pass this info into the `source` keyword without defining (error occurs)
```
# this is a comment: $HOSTNAME=laptop
source=~/.config/hypr/$HOSTNAME.conf
```

**Comment by vaxerski** [comment]
odd, these seem to work on my end. 

![image](https://github.com/hyprwm/hyprlang/assets/43317083/4ce23de2-ca53-46dd-8f92-98bed7211bdf)


![image](https://github.com/hyprwm/hyprlang/assets/43317083/3c805303-4b3c-4f33-866c-aa70bb634169)

**Comment by vaxerski** [comment]
```ini
workspace = special:hi, on-created-empty:foot -H echo $TERMINAL
```
if $TERM is defined, but $TERMINAL isn't, the output of `linuxINAL` is expected, documented and just how it always has been

**Comment by kojq** [comment]
When defined, yeah. The issue is it is no longer considered defined when doing recursive vars.

**Comment by vaxerski** [comment]
please give a minimal reproducible example.

**Comment by kojq** [comment]
from hyprwm/Hyprland/issues/5172:
```
$TERMINAL = alacritty
$comms = [workspace special:hyprake] $TERMINAL --class hyprake
workspace = special:hyprake, on-created-empty:$comms
```

**Comment by kojq** [comment]
`bind = WIN, N, togglespecialworkspace, hyprake`

result is no terminal

**Comment by kojq** [comment]
This should help you see what is happening (linuxINAL):
```
$TERMINAL = foot
$comms = $TERMINAL
workspace = special:hyprake, on-created-empty:foot -H echo $comms
bind = WIN, N, togglespecialworkspace, hyprake
```
