### ISSUE TITLE
Feature request: `hyprctl keyword` keyword to accept devices names again

### ISSUE THREAD

**Issue by sluedecke** [hyprwm/hyprlang#35]
At least as of 0.37.1, hyprctl no longer accepts configuring input devices like `hyprctl keyword device:<device name>:enabled 0`

This affects transformation, e.g. for rotated touchscreens which is handled in `iio-hyprland`, too.

So I kindly request the `keyword` keyword to accept devices names again, or in general keys of categories if thats easy to do as well.

Copied over from which contains more information:
https://github.com/hyprwm/Hyprland/issues/5195

It is mentioned there that this should be an issue against hyprlang.

**Comment by vaxerski** [comment]
syntax suggestions?

I thought about
```ini
device[amogus]:sus
```

**Comment by sluedecke** [comment]
Since `device` seems to be the only one which is not a 'singleton' and is differentiated by `name = ....`, accessing as `device[name]:attribute' makes sense to me.

**Comment by tienbuigia** [comment]
Also, `hyprctl keyword $variable <value>` doesn't work. Is this related?

**Comment by vaxerski** [comment]
wrap it in single quotes to avoid bash parsing it.... man

also if it's supposed to alter a cached setting, like device configs use `hyprctl -r`

**Comment by tienbuigia** [comment]
> wrap it in single quotes to avoid bash parsing it.... man
> 
> also if it's supposed to alter a cached setting, like device configs use `hyprctl -r`

Yes, sorry, mb

And `hyprctl getoption '$variable'` doesn't work.

**Comment by vaxerski** [comment]
it's not an option.

**Comment by vaxerski** [comment]
`cat[key]:value = amongus`

**Comment by sluedecke** [comment]
Thanks for implementing this!  To get a better understanding (I am not very good at reading c++ :( ) this change means that the old command (example `elan9008:00-04f3:2fc4` is my touch device):

`hyprctl keyword device:elan9008:00-04f3:2fc4:transform 1`

is now

`hyprctl keyword "device[elan9008:00-04f3:2fc4]:transform" = 1`

right?

**Comment by vaxerski** [comment]
si
