### ISSUE TITLE
Build fails with GCC version <13.1

### ISSUE THREAD

**Issue by liam-gleason-snhu** [hyprwm/hyprlang#37]
I realize it may be low priority but Hyprlang cannot be built with any versions of GCC older than 13.1 because it depends on the C++20 language feature std::format, support for which was added in that version. As I am on an aarch64 system and still running 12.1, I cannot build Hyprlang to move to a newer version of Hyprland.

**Comment by vaxerski** [comment]
I don't care, hyprland does too.
