### ISSUE TITLE
Prevent errors from showing up if they will be fixed later (e.g. once a Hyprland plugin loads)

### ISSUE THREAD

**Issue by alba4k** [hyprwm/hyprlang#39]
It could be an option to make certain parts of a config file explicitly unable to cause errors, e.g.:

the C way
```
#unsafe

error

#endunsafe
```

the hyprlang way
```
# hyprlang push noerror

error

# hyprlang pop noerror
```

or the rust way (I think this looks the best as it doesn't look like a comment)
```
unsafe {
    error
}
```

**Comment by alba4k** [comment]
Also one could argue these errors should still be showable using something like `hyprctl configerrors`, as that check would be executed only at a specific moment

**Comment by vaxerski** [comment]
```ini
# hyprlang noerror true
blah = blah
# hyprlang noerror false
```
