### ISSUE TITLE
Feature request: Event hook

### ISSUE THREAD

**Issue by luckasRanarison** [hyprwm/hyprlang#4]
Hi there! Thanks for your amazing project.

It would be nice to have the ability to add event hooks inside the configuration and let hyprland queue and handle them instead of running scripts listening on hyprland socket.

As suggested in https://github.com/hyprwm/Hyprland/issues/3291

**Comment by vaxerski** [comment]
that is a feature to be implemented in hyprland. Hyprlang allows this.
