### ISSUE TITLE
Cross Config Conversion !?

### ISSUE THREAD

**Issue by niksingh710** [hyprwm/hyprlang#40]
It has been noticed that Hyprland projects has been growing with an exponential rate.
There are many projects under `hyprwm` those can be used separately without depending on `Hyprland`.

imo a `hyprlangctl` binary would be nice, that can convert a written `hyprlang` config to other standard config formats like `toml` `json` `yaml` enabling a user to use their preferred config format for the desired project.

`hyprlangctl verify config.json` can tell if the written json is acceptable in `hyprlang`.

**Comment by vaxerski** [comment]
most config languages are not compatible with hyprlang

**Comment by niksingh710** [comment]
Yes, I agree with it.
The most relatable I found is `json`

`windowrulev2 = float,class:^(regex)$`
can be written as 
```json
"windowrulev2": [ "float", "class:^(regex)$"]
```

Writing in json will be a hectic task for users, but for projects having less config this can be a nice option. e.g `hyprlock` 

`json` schema can be used to keep the config directed and prone to errors. 
and `hyprlangctl verify` can verify it.

**Comment by vaxerski** [comment]
still cannot work.

And tbh, I don't see the point. No other software ships multiple config language options.

**Comment by niksingh710** [comment]
Reasonable ig.

I will try to create an Unofficial `json` to `hyprlang`, maybe.

> And tbh, I don't see the point. No other software ships multiple config language options.

Agreed, but ig hyprland is getting bigger and maybe sooner or later will set some standards for wayland.
