### ISSUE TITLE
hyprlang doesn't build 

### ISSUE THREAD

**Issue by alekgr** [hyprwm/hyprlang#41]
/home/alek/.cache/paru/clone/hyprlang-git/src/hyprlang/src/config.cpp:12:10: fatal error: VarList.hpp: No such file or directory
   12 | #include "VarList.hpp"
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/hyprlang.dir/build.make:90: CMakeFiles/hyprlang.dir/src/config.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:844: CMakeFiles/hyprlang.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'hyprlang-git-0.2.1.r6.d486806-1': 
error: packages failed to build: hyprlang-git-0.2.1.r6.d486806-1

**Comment by vaxerski** [comment]
for fucks sake again

**Comment by vaxerski** [comment]
fixed
