### ISSUE TITLE
v0.5.2 fails to build on FreeBSD

### ISSUE THREAD

**Issue by jbeich** [hyprwm/hyprlang#46]
Regressed by 554c95a8468c. FreeBSD for [historic reasons](https://lobste.rs/s/ttr8op/lobsters_interview_with_david_chisnall) uses [libcxxrt](https://github.com/libcxxrt/libcxxrt) instead of [libc++abi](https://libcxxabi.llvm.org/). Removing hardcoded `-lc++abi` does help.

Passing `-lc++` and `-lc++-abi` isn't necessary when using C++ compiler as linker. Even when using C (not C++) compiler for linking passing `-lc++abi` (or `-lcxxrt`) is not necessary when linking dynamically as libc++ itself is usually linked against the right C++ runtime.

```
$ c++ --version
FreeBSD clang version 18.1.5 (https://github.com/llvm/llvm-project.git llvmorg-18.1.5-0-g617a15a9eac9)
Target: x86_64-unknown-freebsd15.0
Thread model: posix
InstalledDir: /usr/bin

$ cmake -G Ninja
$ cmake --build .
[1/2] Linking CXX executable hyprlang_test
FAILED: hyprlang_test
: && /usr/bin/c++  -stdlib=libc++ -lc++abi CMakeFiles/hyprlang_test.dir/tests/parse/main.cpp.o -o hyprlang_test  -Wl,-rpath,/a/hyprlang  libhyprlang.so.0.5.2 && :
ld: error: unable to find library -lc++abi
c++: error: linker command failed with exit code 1 (use -v to see invocation)
[2/2] Linking CXX executable hyprlang_fuzz
FAILED: hyprlang_fuzz
: && /usr/bin/c++  -stdlib=libc++ -lc++abi CMakeFiles/hyprlang_fuzz.dir/tests/fuzz/main.cpp.o -o hyprlang_fuzz  -Wl,-rpath,/a/hyprlang  libhyprlang.so.0.5.2 && :
ld: error: unable to find library -lc++abi
c++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by jbeich** [comment]
Even when using C (not C++) compiler for linking passing `-lc++abi` (or `-lcxxrt`) is not necessary when linking dynamically as libc++ itself is usually linked against the right C++ runtime.

**Comment by jbeich** [comment]
FWIW, FreeBSD chose libcxxrt because libc++abi didn't exist at the time. See [David's interview](https://lobste.rs/s/ttr8op/lobsters_interview_with_david_chisnall) for more details.

**Comment by vaxerski** [comment]
so, basically, remove the `-lc++abi`, right?

**Comment by jbeich** [comment]
[Yep](https://github.com/freebsd/freebsd-ports/blob/2f3d1d2641ba/devel/hyprlang/files/patch-CMakeLists.txt)

**Comment by vaxerski** [comment]
sure then
