### ISSUE TITLE
[Feat Req] Optional sourced file

### ISSUE THREAD

**Issue by kRHYME7** [hyprwm/hyprlang#57]
#52 Conditionals is very flexible, but might be too much. So I will start from this part. 

Is it possible to have a flag for ` source` to tell hyprlang to skip or not give errors if file do not exist. Explicit sourcing is robust, but having this option opens a new window of customization.

Examples are ( q for quiet )

```hyprlang
sourceq = /path/that/exist
sourceq = /path/that/may/not/exist
sourceq = /maybe/a/path/where/users/can/add/overrides
```

This can also be used to have a fallback configuration when a distro or a DE wants to have defaults without the USER touching this file.

**Comment by vaxerski** [comment]
hyprlang does not provide source. Source is implemented by users of the library as a keyword. See https://github.com/hyprwm/Hyprland/blob/0e630e9e74ad34683194a07cfe6afe55a2c0685f/src/config/ConfigManager.cpp#L289-L299

**Comment by vaxerski** [comment]
> not give errors if file do not exist

```
# hyprlang noerror true

bind = MOD, KEY, something, amogus
someoption = blah

# hyprlang noerror false
```

**Comment by kRHYME7** [comment]
Thanks
