### ISSUE TITLE
Move libc++ configuration to distribution package maintainers instead of enforcing it when clang is used

### ISSUE THREAD

**Issue by Rudolchr** [hyprwm/hyprlang#59]
Currently, when clang is used as the compiler, the CMake configuration enforces the use of libc++ as the C++ standard library (see [CMakeLists.txt:54](https://github.com/hyprwm/hyprlang/blob/f7acd5dabba315247497bc9f89da2c5e175aa9a1/CMakeLists.txt#L54) and [CMakeLists.txt:55](https://github.com/hyprwm/hyprlang/blob/f7acd5dabba315247497bc9f89da2c5e175aa9a1/CMakeLists.txt#L55)).

In most Linux distributions, the default C++ standard library is libstdc++, and using libc++ with clang usually requires explicit configuration, by setting -stdlib=libc++. I believe it would be more appropriate for the distribution's package maintainers to set this flag, rather than enforcing it directly in the project's build system.

This change would provide greater flexibility for users and avoid conflicts with system-wide library defaults.

Edit:
Reference to this issue https://github.com/hyprwm/hyprlang/issues/47

**Comment by vaxerski** [comment]
sure, IIRC it was added because otherwise clang would fail to build hyprlang.
